Update ios.yml
Check Test Results and Stop if Tests Failed

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -48,9 +48,11 @@ jobs:
         continue-on-error: true
 
       - name: Check Test Results and Stop if Tests Failed
-        if: steps.build_and_test.outcome == 'failure'
+        if: failure()
         run: |
           echo "::error::❌ Unit tests failed. Stopping the workflow."
+          echo "Failed unit tests:"
+          grep -A 5 "Test Case '-\[.*\] failed" xcodebuild.log || true
           exit 1
 
       - name: Confirm xcodebuild.log Generation
